
# remap prefix from 'C-b' to 'C-a'
set -g prefix C-a
unbind C-b
bind-key C-a send-prefix

# split panes using | and -
unbind %
bind | split-window -h -c "#{pane_current_path}"
unbind '"'
bind - split-window -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"

# reload config file (change file location to your the tmux.conf you want to use)
unbind r
bind r source-file ~/.config/tmux/tmux.conf

# Resize panes
bind -r j resize-pane -D 5
bind -r k resize-pane -U 5
bind -r l resize-pane -R 5
bind -r h resize-pane -L 5
bind -r m resize-pane -Z
bind C-p previous-window
bind C-n next-window

# Enable mouse
set -g mouse on

# Terminal scrollback
set -g history-limit 50000

# switch panes using Alt-arrow without prefix
bind -n M-h select-pane -L
bind -n M-l select-pane -R
bind -n M-k select-pane -U
bind -n M-j select-pane -D

# Enable VIM motions
set-window-option -g mode-keys vi
bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'y' send -X copy-selection

# Enable Mouse Dragging
# unbind -T copy-mode-vi MouseDragEnd1Pane

# Enable mouse control (clickable windows, panes, resizable panes)

# don't rename windows automatically
set-option -g allow-rename off

# github.com/tmux-plugins/tmux-sensible
## options
# Address vim mode switching delay (http://superuser.com/a/252717/65504)
set -s escape-time 0

# Increase tmux messages display duration from 750ms to 4s
set -g display-time 4000

# Refresh 'status-left' and 'status-right' more often, from every 15s to 5s
set -g status-interval 5

# Upgrade $TERM
set -g default-terminal "screen-256color"

# Super useful when using "grouped sessions" and multi-monitor setup
setw -g aggressive-resize on

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'jimeh/tmux-themepack'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-ressurect' # tmux sessions persist after restart
set -g @plugin 'tmux-plugins/tmux-continuum' # autosaves sessions each 15 minutes

set -g @ressurect-captire-pane-contents 'on'
set -g @continuum-restore 'on'

set -g @themepack 'powerline/default/gray'

run '~/.tmux/plugins/tpm/tpm'
