# BEGIN_KITTY_THEME
# Catppuccin-Mocha
include belafonte_day.conf
# END_KITTY_THEME
#

font_family JetBrains Mono
bold_font auto
italic_font auto
bold_italic_font auto

font_size 13
modify_font cell_height 110%

background #141415
background_opacity 0.7

dynamic_background_opacity yes
# Increase opacity (less transparent)
map ctrl+shift+. set_background_opacity +0.05
# Decrease opacity (more transparent)
map ctrl+shift+, set_background_opacity -0.05

#Bind mouse scrolling
map ctrl+scroll_up change_font_size all +2.0
map ctrl+scroll_down change_font_size all -2.0
map ctrl+0 change_font_size all 0
